# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from path_finder/ard.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ard(genpy.Message):
  _md5sum = "5ab222d10bef5cb8f3d8c151fb86bd8b"
  _type = "path_finder/ard"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 ult_right
float64 ult_left
float64 ir_right
float64 ir_left
float64 compass_x
float64 compass_y
float64 compass_z
uint64 servo_angle
"""
  __slots__ = ['ult_right','ult_left','ir_right','ir_left','compass_x','compass_y','compass_z','servo_angle']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','uint64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ult_right,ult_left,ir_right,ir_left,compass_x,compass_y,compass_z,servo_angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ard, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ult_right is None:
        self.ult_right = 0.
      if self.ult_left is None:
        self.ult_left = 0.
      if self.ir_right is None:
        self.ir_right = 0.
      if self.ir_left is None:
        self.ir_left = 0.
      if self.compass_x is None:
        self.compass_x = 0.
      if self.compass_y is None:
        self.compass_y = 0.
      if self.compass_z is None:
        self.compass_z = 0.
      if self.servo_angle is None:
        self.servo_angle = 0
    else:
      self.ult_right = 0.
      self.ult_left = 0.
      self.ir_right = 0.
      self.ir_left = 0.
      self.compass_x = 0.
      self.compass_y = 0.
      self.compass_z = 0.
      self.servo_angle = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7dQ().pack(_x.ult_right, _x.ult_left, _x.ir_right, _x.ir_left, _x.compass_x, _x.compass_y, _x.compass_z, _x.servo_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.ult_right, _x.ult_left, _x.ir_right, _x.ir_left, _x.compass_x, _x.compass_y, _x.compass_z, _x.servo_angle,) = _get_struct_7dQ().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7dQ().pack(_x.ult_right, _x.ult_left, _x.ir_right, _x.ir_left, _x.compass_x, _x.compass_y, _x.compass_z, _x.servo_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.ult_right, _x.ult_left, _x.ir_right, _x.ir_left, _x.compass_x, _x.compass_y, _x.compass_z, _x.servo_angle,) = _get_struct_7dQ().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7dQ = None
def _get_struct_7dQ():
    global _struct_7dQ
    if _struct_7dQ is None:
        _struct_7dQ = struct.Struct("<7dQ")
    return _struct_7dQ
